In [ ]:
#1 + 1 

[1] 2

# Ejemplo de markdown 

Esto es una prueba 
## Titulo 2

Esto es una prueba 

## Titulo 3

Esto es una prueba 


# Titulo 4

[Enlace](https://google.com)

$$ z^2 = x^2 + y^2  $$

Esta es una ecuación $ \alpha = \beta + 1 $.


| Altura | Peso |
|--------|------|
| 1.7    | 150  |


# Operadores en R 

In [ ]:
2 + 2

[1] 4

In [ ]:
1 + 2 * 3 

[1] 7

In [ ]:
(1 + 2) * 3 

[1] 9

In [ ]:
(2 * 2) == 4

[1] TRUE

In [ ]:
pi 

[1] 3.141593

In [ ]:
pi >= 10

[1] FALSE

In [ ]:
pi < 1

[1] FALSE

# Variables

Digamos que una persona pesa 55 kilogramos y queremos almacenar esta información en una variable, esto lo podes hacer de la siguiente manera. 

In [ ]:
weight_kg1 = 55

In [ ]:
weight_kg2 <- 55

In [ ]:
weight_kg1 == weight_kg2

[1] TRUE

De aqui en adelante vamos a usar el operador de asignación <- en lugar del =. La elección de esto es por conveniencia, sin embargo, en un ambiente profesional se le podria dar mas prioridad al =. 

In [ ]:
hola mundo <- 10 # no es un nombre valido de variable.

ERROR: ignored

In [ ]:
canción <- "el himno de la alegria"

In [ ]:
canción

[1] "el himno de la alegria"

Poner acentos en las variables es una mala práctica, no lo hagan puede crear confusión con personas que no hablen español. 

In [ ]:
2.2 * weight_kg1 # haciendo aritmetica con variables

[1] 121

In [ ]:
weight_kg1 <- 57.5 # reasignando valores 
weight_kg1

[1] 57.5

In [ ]:
weight_kg1 <- 2.2 * weight_kg1
weight_kg1 

[1] 126.5

In [ ]:
weight_lb1 <- 2.2 * weight_kg1
weight_lb1
weight_kg1

[1] 278.3

[1] 126.5

In [ ]:
weight_kg1 <- 100.0 
weight_kg1

[1] 100

In [ ]:
weight_lb1

[1] 278.3

# Vectores

Un vector de numeros es una colección de numeros. Los miembros individuales se les llama elementos. 

In [ ]:
myvec <- c(10, 20, 30, 40, 50) # creamos un vector numerico de 5 elementos.

In [ ]:
myvec

[1] 10 20 30 40 50

In [ ]:
str(myvec)

 num [1:5] 10 20 30 40 50


In [ ]:
myvec + 1 

[1] 11 21 31 41 51

In [ ]:
myvec + myvec 

[1]  20  40  60  80 100

In [ ]:
length(myvec)

[1] 5

In [ ]:
c(60, myvec)

[1] 60 10 20 30 40 50

In [ ]:
myvec2 <- c(60, myvec)

In [ ]:
myvec2

[1] 60 10 20 30 40 50

In [ ]:
c(myvec, myvec)

[1] 10 20 30 40 50 10 20 30 40 50

Crear un vector con las notas que obtuviste el anterior ciclo y asignarlo a la variable notas.

In [ ]:
notas <- c(10, 7, 8, 9)
notas

[1] 10  7  8  9

## Tipos de vectores 

In [ ]:
vector_cadenas = c("hola", "mundo") # vector de cadenas

In [ ]:
vector_cadenas

[1] "hola"  "mundo"

In [ ]:
vector_logicos = c(TRUE, FALSE, TRUE, TRUE) # vector de valores logicos
vector_logicos

[1]  TRUE FALSE  TRUE  TRUE

¿Que pasa si creo un vector que tenga a su vez valores númericos y valores tipo cadena (string)? 

In [ ]:
vector_logico_y_cadena = c(10, "Hola", 9, "mundo")

In [ ]:
vector_logico_y_cadena

[1] "10"    "Hola"  "9"     "mundo"

In [ ]:
vector_enteros_y_flotantes = c(10, 10.9, pi)
vector_enteros_y_flotantes

[1] 10.000000 10.900000  3.141593

## Indexamiento de vectores

In [ ]:
myvec

[1] 10 20 30 40 50

In [ ]:
myvec[1] # accesando al primer elemento 

[1] 10

In [ ]:
myvec[2]

[1] 20

In [ ]:
myvec[2] <- 5

In [ ]:
myvec

[1] 10  5 30 40 50

¿Podemos usar un vector para indexar un vector? 

In [ ]:
myvec[c(4, 3, 2)]

[1] 40 30  5

In [ ]:
myind <- c(4, 3, 4)
myvec[myind]

[1] 40 30 40

In [ ]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
myvec[2:4]

[1]  5 30 40

In [ ]:
myvec[4:2]

[1] 40 30  5

In [ ]:
10:5

[1] 10  9  8  7  6  5

In [ ]:
1:50

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

¿Como obtener de los números del 1 al 10 sus cuadrados? 

In [ ]:
numbers <- 1:10 

In [ ]:
numbers * numbers

[1]   1   4   9  16  25  36  49  64  81 100

In [ ]:
numbers^2 

[1]   1   4   9  16  25  36  49  64  81 100

Ejercicio:

In [ ]:
phrase <- c("Yo", "no", "se", "Yo", "se")

In [ ]:
phrase[1:3]

[1] "Yo" "no" "se"

In [ ]:
phrase[3:5]

[1] "se" "Yo" "se"

In [ ]:
phrase[3:] # no se puede dejar vacio el elemento final si uso el operador secuencia :.

ERROR: ignored

¿Del vector phrase yo se que las primeras 4 palabras las puedo obtener con phrase[1:4]. Como puedo obtener las primeras 4 palabras pero en reversa. 

In [ ]:
phrase[1:4]

[1] "Yo" "no" "se" "Yo"

In [ ]:
phrase[4:1]

[1] "Yo" "se" "no" "Yo"

Probar lo siguiente y deducir que pasa:  
* phrase[-2]
* phrase[-5]
* phrase[-1:-3]



In [ ]:
phrase

[1] "Yo" "no" "se" "Yo" "se"

In [ ]:
phrase[-2]

[1] "Yo" "se" "Yo" "se"

In [ ]:
phrase = c("uno","dos","tres","cuatro","cinco")

In [ ]:
phrase

[1] "uno"    "dos"    "tres"   "cuatro" "cinco"

In [ ]:
phrase[-2]

[1] "uno"    "tres"   "cuatro" "cinco"

In [ ]:
phrase[-5]

[1] "uno"    "dos"    "tres"   "cuatro"

In [ ]:
phrase[-1:-3]

[1] "cuatro" "cinco"

De: 

phrase = c("uno","dos","tres","cuatro","cinco")

Quitar los elementos dos y cuatro.

In [ ]:
phrase = c("uno","dos","tres","cuatro","cinco")

In [ ]:
phrase <- phrase[c(-2, -4)]

In [ ]:
phrase

[1] "uno"   "tres"  "cinco"

# Funciones

Vamos a revisar la función sum que actua sobre vectores.

In [ ]:
?sum  # con ? accedo a la ayuda

In [ ]:
sum(myvec)

[1] 135

In [ ]:
myvec

[1] 10  5 30 40 50

In [ ]:
sum(myvec, myvec)

[1] 270

In [ ]:
myvec3 <- c(10, 15, 7, NA, 0)

In [ ]:
myvec3

[1] 10 15  7 NA  0

In [ ]:
?NA

In [ ]:
is.na(myvec3)

[1] FALSE FALSE FALSE  TRUE FALSE

In [ ]:
sum(is.na(myvec3)) # cuantos NA's hay.

[1] 1

In [ ]:
sum(myvec3)

[1] NA

In [ ]:
sum(myvec3, na.rm=TRUE)

[1] 32

Puedo calcular la suma de los valores diferentes a null usando el hecho que is.na(myvec3) te da los indices de los elementos que son na como TRUE entonces con el operador ! puedo negarlo y luego hacer la suma. Pero este codigo es peligroso muy dificil de leer y no recomendable de manera profesional, hay que tratar de escribir código legible.

In [ ]:
myvec3

[1] 10 15  7 NA  0

In [ ]:
index_not_na = !is.na(myvec3)
index_not_na 

[1]  TRUE  TRUE  TRUE FALSE  TRUE

In [ ]:
sum(myvec3[index_not_na]) # este codigo es confuso y solo se ha hecho 
                          # para efectos pedagogicos, es mucho mejor 
                          # sum(myvec3, na.rm=TRUE)

[1] 32

In [ ]:
?rep

In [ ]:
?sum

Repetir el valor 42 unas 10 veces en un vector, lo puedo hacer con rep.

In [ ]:
rep(42, 10)

[1] 42 42 42 42 42 42 42 42 42 42

In [ ]:
rep(c(1, 2, 3), 10)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(c(1,2,3), times=10)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(x=c(1,2,3), times=10)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(times=10, x=c(1,2,3))

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(10, c(1,2,3))

ERROR: ignored

In [ ]:
rep(c(1,2,3), times=10)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(c(1,2,3), times=10, each=1)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [ ]:
rep(c(1,2,3), times=10, each=2)

[1] 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1
[39] 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3 1 1 2 2 3 3

In [ ]:
rep(c(1,2,3), times=10, each=4)

[1] 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1
 [38] 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1
 [75] 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1 1 2 2 2 2 3 3 3 3 1 1 1
[112] 1 2 2 2 2 3 3 3 3

# Listas

In [ ]:
my_list <- list(num=42, greeting="Hello world")

In [ ]:
my_list

$num
[1] 42

$greeting
[1] "Hello world"

In [ ]:
my_list$num

[1] 42

In [ ]:
my_list$greeting

[1] "Hello world"

In [ ]:
my_list[1] # Me devuelve el elemento 1 como una lista. 

$num
[1] 42

In [ ]:
my_list[[1]] # Accesando al elemento num de la lista.  

[1] 42

In [ ]:
my_list[[2]]

[1] "Hello world"

Ejemplo de como nombrar los elementos de un vector. 

In [ ]:
numeros <- c(1, 2, 3)

In [ ]:
numeros

[1] 1 2 3

In [ ]:
names(numeros)

NULL

In [ ]:
names(numeros) <- c("primero", "segundo", "tercero")

In [ ]:
numeros

primero segundo tercero 
      1       2       3

Si no estoy seguro del tipo de objeto puedo usar las siguientes funciones: 


In [ ]:
class(myvec)

[1] "numeric"

In [ ]:
typeof(myvec)

[1] "double"

In [ ]:
str(myvec)

 num [1:5] 10 5 30 40 50


In [ ]:
class(my_list)

[1] "list"

In [ ]:
typeof(my_list)

[1] "list"

In [ ]:
str(my_list)

List of 2
 $ num     : num 42
 $ greeting: chr "Hello world"


**Ejercicios propuestos**

In [ ]:
sum(1:5)

[1] 15

In [ ]:
sum(1:10000)

[1] 50005000

In [ ]:
(10000*10001)/2

[1] 50005000

In [ ]:
help(seq)

In [ ]:
seq(from=1, to=100, by=2) # numeros impares entre 1 y 100

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

In [ ]:
seq(from=2, to=100, by=2)

[1]   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38
[20]  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
[39]  78  80  82  84  86  88  90  92  94  96  98 100

In [ ]:
seq(from=1, to=100, by=2)  +  1

[1]   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38
[20]  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76
[39]  78  80  82  84  86  88  90  92  94  96  98 100

# Matrices

In [ ]:
x <- 1:9 

In [ ]:
x

[1] 1 2 3 4 5 6 7 8 9

In [ ]:
m <- matrix(x)

In [ ]:
m

[,1]
 [1,] 1   
 [2,] 2   
 [3,] 3   
 [4,] 4   
 [5,] 5   
 [6,] 6   
 [7,] 7   
 [8,] 8   
 [9,] 9

Lo que quiero es la siguiente matriz: 


$$\begin{bmatrix}1 & 4 & 7\\
2 & 5 & 8\\
3 & 6 & 9
\end{bmatrix}$$


In [ ]:
?matrix

In [ ]:
m <- matrix(x, ncol=3)

In [ ]:
m

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
m <- matrix(x, ncol=3, byrow=FALSE)

In [ ]:
m

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
m <- matrix(x, ncol=3, byrow=TRUE)

In [ ]:
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [ ]:
m + m 

[,1] [,2] [,3]
[1,]  2    4    6  
[2,]  8   10   12  
[3,] 14   16   18

In [ ]:
solve(m)

ERROR: ignored

In [ ]:
m2 = matrix(c(4,2,1,5), ncol=2)

In [ ]:
m2

[,1] [,2]
[1,] 4    1   
[2,] 2    5

In [ ]:
solve(m2)

[,1]       [,2]       
[1,]  0.2777778 -0.05555556
[2,] -0.1111111  0.22222222

In [ ]:
m3 <- solve(m2)

In [ ]:
m2 %*% m3

[,1]         [,2]
[1,] 1.000000e+00 0   
[2,] 5.551115e-17 1

In [ ]:
m3

[,1]       [,2]       
[1,]  0.2777778 -0.05555556
[2,] -0.1111111  0.22222222

In [ ]:
m3[1, ] # accesando a la primera fila

[1]  0.27777778 -0.05555556

In [ ]:
m3[, 2]  # accesando a la segunda columna 

[1] -0.05555556  0.22222222

In [ ]:
m4 <- matrix(1:16, ncol=4)

In [ ]:
m4

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [ ]:
m4[, c(2, 4)]

[,1] [,2]
[1,] 5    13  
[2,] 6    14  
[3,] 7    15  
[4,] 8    16

In [ ]:
m4[1:2, ]

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14

In [ ]:
m4[c(1,2), ]

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14

In [ ]:
m4

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

Puedo nombrar las columnas y filas.

In [ ]:
colnames(m4)

NULL

In [ ]:
rownames(m4)

NULL

In [ ]:
colnames(m4) <- c("C1", "C2", "C3", "C4")

In [ ]:
m4

C1 C2 C3 C4
[1,] 1  5   9 13
[2,] 2  6  10 14
[3,] 3  7  11 15
[4,] 4  8  12 16

In [ ]:
rownames(m4) <- c("R1", "R2", "R3", "R4")

In [ ]:
m4

C1 C2 C3 C4
R1 1  5   9 13
R2 2  6  10 14
R3 3  7  11 15
R4 4  8  12 16

In [ ]:
m4[C1, ]

ERROR: ignored

In [ ]:
m4["R1", ]

C1 C2 C3 C4 
 1  5  9 13

In [ ]:
m4[, "C1"]

R1 R2 R3 R4 
 1  2  3  4

In [ ]:
?as.matrix

In [ ]:
x2 <- seq(1, 2, by=0.1)
x2

[1] 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0

In [ ]:
m5 <- as.matrix(x2)

In [ ]:
m5

[,1]
 [1,] 1.0 
 [2,] 1.1 
 [3,] 1.2 
 [4,] 1.3 
 [5,] 1.4 
 [6,] 1.5 
 [7,] 1.6 
 [8,] 1.7 
 [9,] 1.8 
[10,] 1.9 
[11,] 2.0

In [ ]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
m6 <- matrix(letters[1:16], ncol=4)

In [ ]:
m6

[,1] [,2] [,3] [,4]
[1,] a    e    i    m   
[2,] b    f    j    n   
[3,] c    g    k    o   
[4,] d    h    l    p

In [ ]:
solve(m6)

ERROR: ignored

# Data Frames

In [ ]:
x1 = 1:16 
x2 = letters[1:16]
x3 = rnorm(16)

In [ ]:
x1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16

In [ ]:
x2

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p"

In [ ]:
x3

[1]  0.1271303 -0.2107701 -0.4246119 -0.1401276 -1.1907096  0.2520309
 [7]  0.9206727  1.2738698  2.1257802 -0.9826555 -0.2014291  1.0011734
[13]  1.0413929  0.7416404  1.0263163 -0.1540825

In [ ]:
df1 <- data.frame(numeros = x1, letras = x2, normales=x3)

In [ ]:
df1

numeros letras normales  
1   1      a       0.1271303
2   2      b      -0.2107701
3   3      c      -0.4246119
4   4      d      -0.1401276
5   5      e      -1.1907096
6   6      f       0.2520309
7   7      g       0.9206727
8   8      h       1.2738698
9   9      i       2.1257802
10 10      j      -0.9826555
11 11      k      -0.2014291
12 12      l       1.0011734
13 13      m       1.0413929
14 14      n       0.7416404
15 15      o       1.0263163
16 16      p      -0.1540825

In [ ]:
df1[,"numeros"]

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16

In [ ]:
df1[,c("numeros", "normales")]

numeros normales  
1   1       0.1271303
2   2      -0.2107701
3   3      -0.4246119
4   4      -0.1401276
5   5      -1.1907096
6   6       0.2520309
7   7       0.9206727
8   8       1.2738698
9   9       2.1257802
10 10      -0.9826555
11 11      -0.2014291
12 12       1.0011734
13 13       1.0413929
14 14       0.7416404
15 15       1.0263163
16 16      -0.1540825

In [ ]:
df2 <- df1[,c("numeros", "normales")]

In [ ]:
df2

numeros normales  
1   1       0.1271303
2   2      -0.2107701
3   3      -0.4246119
4   4      -0.1401276
5   5      -1.1907096
6   6       0.2520309
7   7       0.9206727
8   8       1.2738698
9   9       2.1257802
10 10      -0.9826555
11 11      -0.2014291
12 12       1.0011734
13 13       1.0413929
14 14       0.7416404
15 15       1.0263163
16 16      -0.1540825

In [ ]:
as.matrix(df2)

numeros normales  
 [1,]  1       0.1271303
 [2,]  2      -0.2107701
 [3,]  3      -0.4246119
 [4,]  4      -0.1401276
 [5,]  5      -1.1907096
 [6,]  6       0.2520309
 [7,]  7       0.9206727
 [8,]  8       1.2738698
 [9,]  9       2.1257802
[10,] 10      -0.9826555
[11,] 11      -0.2014291
[12,] 12       1.0011734
[13,] 13       1.0413929
[14,] 14       0.7416404
[15,] 15       1.0263163
[16,] 16      -0.1540825

In [ ]:
df1$letras

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p"

In [ ]:
m6

[,1] [,2] [,3] [,4]
[1,] a    e    i    m   
[2,] b    f    j    n   
[3,] c    g    k    o   
[4,] d    h    l    p

In [ ]:
df3 <- as.data.frame(m6)

In [ ]:
df3

V1 V2 V3 V4
1 a  e  i  m 
2 b  f  j  n 
3 c  g  k  o 
4 d  h  l  p

In [ ]:
m4

C1 C2 C3 C4
R1 1  5   9 13
R2 2  6  10 14
R3 3  7  11 15
R4 4  8  12 16

In [ ]:
df4 <- as.data.frame(m4)

In [ ]:
df4

C1 C2 C3 C4
R1 1  5   9 13
R2 2  6  10 14
R3 3  7  11 15
R4 4  8  12 16

 # Funciones de resumenes de datos

In [ ]:
max(df4)

[1] 16

In [ ]:
max(df4$C1)

[1] 4

In [ ]:
max(df3)

ERROR: ignored

In [ ]:
head(df1)

numeros letras normales  
1 1       a       0.1271303
2 2       b      -0.2107701
3 3       c      -0.4246119
4 4       d      -0.1401276
5 5       e      -1.1907096
6 6       f       0.2520309

In [ ]:
max(df1)

ERROR: ignored

In [ ]:
vec1 <- rnorm(100)

In [ ]:
vec1

[1]  1.3180179240 -0.0225040475  0.2345377609 -0.2725175855 -0.2801968364
  [6]  0.3534042958  0.0786409935 -0.4228483532  0.8909992347 -0.3221174807
 [11]  0.6461270252  0.4093657940 -0.2393917955 -0.6738188242  1.0833989257
 [16] -0.0470088872 -1.1873261632  0.8630136653 -1.1128000087 -0.1752209303
 [21] -0.0007897251 -0.5112039752 -0.1178595844  1.1234543107 -1.0212256901
 [26] -1.6956376965 -0.4511093683 -1.0753880644 -0.4433821272  2.1304065683
 [31] -1.1230994686  0.7953077300 -1.2155159903 -2.5582982080  0.2001350438
 [36]  0.2129488132  0.1214534543  0.9325616192  0.7443402067 -0.3577602841
 [41]  1.0601957722 -0.0454378914 -0.1970240732  0.1553411250  0.4335252692
 [46]  0.5694391747  0.1695274654 -0.2479282514  1.6674895990  0.8810436476
 [51]  1.1930648769  0.4900429925 -0.0890127034  0.2316445771 -0.4862900830
 [56] -1.0158821138  1.1985557876 -2.1897476571  1.3152111493  0.9461729887
 [61] -0.4655745016 -0.5389238085  0.9186867135  0.0917786476  1.2999645295
 [66]  0.2870425002 -0.1454363429  0.8305432417 -0.9931731932  0.3822457761
 [71] -0.6892698615 -0.4800749607 -0.5663282468  0.0150278630  0.8905351789
 [76] -0.4322795999  0.2386019536  1.7808273805  1.2390150716 -0.5621090534
 [81]  2.1749088829 -0.2967828347  1.3914947378 -0.2943295044 -1.1813695918
 [86] -1.1408707225  0.7221572351 -0.3323235459 -0.1100814952  1.8499911147
 [91] -1.8893432309 -0.8254400774  0.8313743375  0.5992124167  0.8653146388
 [96]  0.7483405075 -1.0909152108 -0.6324306045  0.6511263488  1.4340499262

In [ ]:
max(vec1) # maximo

[1] 2.174909

In [ ]:
min(vec1) # minimo

[1] -2.558298

In [ ]:
mean(vec1) # media

[1] 0.09426207

In [ ]:
median(vec1) # mediana

[1] 0.04683443

In [ ]:
var(vec1) # varianza

[1] 0.8547895

In [ ]:
sd(vec1)

[1] 0.9245483

# Resumiendo matrices

In [ ]:
m4

C1 C2 C3 C4
R1 1  5   9 13
R2 2  6  10 14
R3 3  7  11 15
R4 4  8  12 16

In [ ]:
?apply

In [ ]:
apply(m4, 2, mean)

C1   C2   C3   C4 
 2.5  6.5 10.5 14.5

In [ ]:
apply(m4, 2, median)

C1   C2   C3   C4 
 2.5  6.5 10.5 14.5

Calcular la suma por filas. 

In [ ]:
apply(m4, 1, sum)

R1 R2 R3 R4 
28 32 36 40

In [ ]:
colMeans(m4)

C1   C2   C3   C4 
 2.5  6.5 10.5 14.5

In [ ]:
rowMeans(m4)

R1 R2 R3 R4 
 7  8  9 10

# Prueba t-student

In [ ]:
x <- c(36.25, 35.40, 35.30, 35.15, 35.35, 33.35)

In [ ]:
m7 <- matrix(x, ncol=3, byrow = TRUE)

In [ ]:
m7

[,1]  [,2]  [,3] 
[1,] 36.25 35.40 35.30
[2,] 35.15 35.35 33.35

In [ ]:
colnames(m7) <- c("Alicia", "Veronica", "Carlos")

In [ ]:
m7

Alicia Veronica Carlos
[1,] 36.25  35.40    35.30 
[2,] 35.15  35.35    33.35

In [ ]:
m7[1, ]

Alicia Veronica   Carlos 
   36.25    35.40    35.30

In [ ]:
m7[2, ]

Alicia Veronica   Carlos 
   35.15    35.35    33.35

In [ ]:
t.test(m7[1, ], m7[2, ]) # realiza una prueba t de dos muestras
                        # con datos no-pareados.


	Welch Two Sample t-test

data:  m7[1, ] and m7[2, ]
t = 1.4683, df = 2.8552, p-value = 0.2427
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.271985  3.338652
sample estimates:
mean of x mean of y 
 35.65000  34.61667 


In [ ]:
t.test(m7[1, ], m7[2, ], paired=TRUE)  # realiza una prueba t de dos muestras
                                      # con datos pareados.


	Paired t-test

data:  m7[1, ] and m7[2, ]
t = 1.8805, df = 2, p-value = 0.2008
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.330952  3.397618
sample estimates:
mean of the differences 
               1.033333 
